-- 코드를 작성해주세요
SELECT FISH_COUNT, FISH_NAME
FROM (
    SELECT FISH_TYPE, COUNT(*) AS FISH_COUNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS A
LEFT JOIN FISH_NAME_INFO
ON FISH_NAME_INFO.FISH_TYPE = A.FISH_TYPE
ORDER BY FISH_COUNT DESC