-- 코드를 작성해주세요
SELECT SCORE, HR_EMPLOYEES.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1
) AS A
JOIN HR_EMPLOYEES
ON HR_EMPLOYEES.EMP_NO = A.EMP_NO