-- 코드를 입력하세요
SELECT CAR_ID, IF(USING_CAR_ID IS NULL, "대여 가능", "대여중") AS AVAILABILITY
FROM (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
) AS A
LEFT JOIN (
    SELECT CAR_ID AS USING_CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE("2022-10-16") >= START_DATE AND DATE("2022-10-16") <= END_DATE
    GROUP BY CAR_ID
) AS B
ON A.CAR_ID = B.USING_CAR_ID
ORDER BY CAR_ID DESC