-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT FAVORITES, MAX(FAVORITES) OVER(PARTITION BY FOOD_TYPE) AS MAX_FAVORITES, REST_NAME, FOOD_TYPE, REST_ID
    FROM REST_INFO
) AS A
WHERE FAVORITES = MAX_FAVORITES
ORDER BY FOOD_TYPE DESC