-- 코드를 입력하세요
SELECT MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM (
    SELECT *
    FROM (
        SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) OVER(PARTITION BY CAR_ID) AS RECORDS_BY_CAR
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10 AND YEAR(START_DATE) = 2022
    ) AS A
    WHERE RECORDS_BY_CAR >= 5
) AS B
GROUP BY CAR_ID, MONTH
HAVING RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC