-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM (
    SELECT SUM(PRICE) AS TOTAL_SALES, USER_ID, NICKNAME
    FROM USED_GOODS_BOARD
    JOIN USED_GOODS_USER
    ON USED_GOODS_BOARD.WRITER_ID = USED_GOODS_USER.USER_ID
    WHERE STATUS = "DONE"
    GROUP BY USER_ID
) AS A
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC