-- 코드를 작성해주세요
SELECT FISH_COUNT, MAX_LENGTH, FISH_TYPE
FROM (
    SELECT AVG(LENGTH) AS AVG_LENGTH, MAX(LENGTH) AS MAX_LENGTH, COUNT(*) AS FISH_COUNT, FISH_TYPE
    FROM (
        SELECT FISH_TYPE, IFNULL(LENGTH, 10) AS LENGTH
        FROM FISH_INFO
    ) AS B
    GROUP BY FISH_TYPE
) AS A
WHERE AVG_LENGTH >= 33
ORDER BY FISH_TYPE ASC