-- 코드를 작성해주세요
SELECT HR_DEPARTMENT.DEPT_ID, DEPT_NAME_EN, AVG_SAL
FROM (
    SELECT DEPT_ID, ROUND(AVG(SAL)) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
) AS A
JOIN HR_DEPARTMENT
ON HR_DEPARTMENT.DEPT_ID = A.DEPT_ID
ORDER BY AVG_SAL DESC