-- 코드를 입력하세요
SELECT FOOD_PRODUCT.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) AS A ON FOOD_PRODUCT.CATEGORY = A.CATEGORY
WHERE MAX_PRICE = PRICE
AND (A.CATEGORY = "과자" OR A.CATEGORY = "국" OR A.CATEGORY = "김치" OR A.CATEGORY = "식용유")
ORDER BY MAX_PRICE DESC