-- 코드를 입력하세요
SELECT BOOK.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK_SALES
JOIN BOOK ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
JOIN AUTHOR ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
WHERE YEAR(SALES_DATE) = 2022
AND MONTH(SALES_DATE) = 1
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY BOOK.AUTHOR_ID ASC, CATEGORY DESC