-- 코드를 입력하세요
WITH RECURSIVE A AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 AS HOUR
    FROM A
    WHERE HOUR < 23
)
SELECT A.HOUR, IFNULL(B.COUNT, 0) AS COUNT
FROM A
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
    ORDER BY HOUR ASC
) AS B
ON A.HOUR = B.HOUR