-- 코드를 입력하세요
SELECT CART_ID
FROM (
    SELECT CART_ID, MAX(IF(NAME = "Milk", 1, 0)) AS IS_MILK, MAX(IF(NAME = "Yogurt", 1, 0)) AS IS_YOGURT
    FROM CART_PRODUCTS
    GROUP BY CART_ID
) AS A
WHERE IS_MILK = 1 AND IS_YOGURT = 1
ORDER BY CART_ID ASC