-- 코드를 작성해주세요
SELECT ITEM_INFO.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
LEFT JOIN (
    SELECT ITEM_ID, COUNT(*) AS CHILD_NUM
    FROM (
        SELECT A.ITEM_ID, B.ITEM_ID AS CHILD_ID
        FROM ITEM_TREE AS A
        JOIN ITEM_TREE AS B
        ON A.ITEM_ID = B.PARENT_ITEM_ID
    ) AS C
    GROUP BY ITEM_ID
) AS D
ON ITEM_INFO.ITEM_ID = D.ITEM_ID
WHERE CHILD_NUM IS NULL
ORDER BY ITEM_INFO.ITEM_ID DESC