-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO
LEFT JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS A ON A.FISH_TYPE = FISH_INFO.FISH_TYPE
LEFT JOIN FISH_NAME_INFO ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
WHERE MAX_LENGTH = LENGTH
ORDER BY ID


-- RANK를 통한 구현
SELECT ID, FISH_NAME_INFO.FISH_NAME, LENGTH
FROM (
    SELECT ID, FISH_TYPE, RANKING, LENGTH
    FROM (
        SELECT ID, FISH_TYPE, LENGTH, RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RANKING
        FROM FISH_INFO
    ) AS A
    WHERE RANKING = 1
) AS B
LEFT JOIN FISH_NAME_INFO ON FISH_NAME_INFO.FISH_TYPE = B.FISH_TYPE
ORDER BY ID ASC