-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW
JOIN MEMBER_PROFILE
ON REST_REVIEW.MEMBER_ID = MEMBER_PROFILE.MEMBER_ID
WHERE REST_REVIEW.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM (
        SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT, MAX(COUNT(*)) OVER() AS MAX_REVIEW_COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) AS A
    WHERE MAX_REVIEW_COUNT = REVIEW_COUNT
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC