-- 코드를 입력하세요
SELECT CAR_RENTAL_COMPANY_CAR.CAR_ID, CAR_RENTAL_COMPANY_CAR.CAR_TYPE, FLOOR(DAILY_FEE * RATE_TABLE.RATE * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR
JOIN (
    SELECT CAR_TYPE, (1 - DISCOUNT_RATE / 100) AS RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = "30일 이상"
) AS RATE_TABLE
ON CAR_RENTAL_COMPANY_CAR.CAR_TYPE = RATE_TABLE.CAR_TYPE
WHERE (CAR_RENTAL_COMPANY_CAR.CAR_TYPE = "세단" OR CAR_RENTAL_COMPANY_CAR.CAR_TYPE = "SUV")
    AND CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE (START_DATE <= DATE("2022-11-01") AND DATE("2022-11-01") < END_DATE)
            OR(START_DATE <= DATE("2022-11-30") AND DATE("2022-11-30") < END_DATE)
        GROUP BY CAR_ID
    )
    AND DAILY_FEE * RATE_TABLE.RATE * 30 >= 500000
    AND DAILY_FEE * RATE_TABLE.RATE * 30 < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_RENTAL_COMPANY_CAR.CAR_ID DESC