-- 코드를 입력하세요
SELECT YEAR, MONTH, PURCHASED_USERS, ROUND(PURCHASED_USERS / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PURCHASED_RATIO
FROM (
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT ONLINE_SALE.USER_ID) AS PURCHASED_USERS
    FROM ONLINE_SALE
    JOIN USER_INFO
    ON ONLINE_SALE.USER_ID = USER_INFO.USER_ID
    WHERE YEAR(JOINED) = 2021
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
) AS A
ORDER BY YEAR ASC, MONTH ASC