-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) AS `전체주소`, CONCAT(LEFT(TLNO, 3), "-", MID(TLNO, 4, 4), "-", RIGHT(TLNO, 4)) AS `전화번호`
FROM (
    SELECT WRITER_ID, COUNT(*) AS BOARD_COUNT
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
) AS A
JOIN USED_GOODS_USER
ON USED_GOODS_USER.USER_ID = A.WRITER_ID
WHERE BOARD_COUNT >= 3
ORDER BY USER_ID DESC