-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/", A.BOARD_ID, "/", FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM (
    SELECT BOARD_ID, VIEWS, MAX(VIEWS) OVER() AS MAX_VIEWS
    FROM USED_GOODS_BOARD
) AS A
LEFT JOIN USED_GOODS_FILE
ON USED_GOODS_FILE.BOARD_ID = A.BOARD_ID
WHERE VIEWS = MAX_VIEWS
ORDER BY FILE_ID DESC