-- 코드를 작성해주세요
SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
LEFT JOIN SKILLCODES ON DEVELOPERS.SKILL_CODE & SKILLCODES.CODE != 0
WHERE SKILLCODES.NAME = "Python" OR SKILLCODES.NAME = "C#"
ORDER BY ID ASC