-- 코드를 작성해주세요
SELECT 
    ID,
    CASE
        WHEN (RankValue / TotalSize) * 100 <= 25 THEN "CRITICAL"
        WHEN (RankValue / TotalSize) * 100 <= 50 THEN "HIGH"
        WHEN (RankValue / TotalSize) * 100 <= 75 THEN "MEDIUM"
        ELSE "LOW"
    END AS COLONY_NAME
FROM (
    SELECT 
        ID,
        SIZE_OF_COLONY,
        RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RankValue,
        (SELECT COUNT(*) FROM ECOLI_DATA) AS TotalSize
    FROM ECOLI_DATA
) AS A
ORDER BY ID ASC

-- PERCENT_RANK를 통한 구현
SELECT
    ID,
    CASE
        WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) <= 0.25 THEN "CRITICAL"
        WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) <= 0.5 THEN "HIGH"
        WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) <= 0.75 THEN "MEDIUM"
        ELSE "LOW"
    END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID ASC
