-- 코드를 작성해주세요
SELECT THIRD_GEN.ID
FROM (
    SELECT B.ID
    FROM ECOLI_DATA AS A
    INNER JOIN ECOLI_DATA AS B ON A.ID = B.PARENT_ID
    WHERE A.PARENT_ID IS NULL
) AS SECOND_GEN
INNER JOIN ECOLI_DATA AS THIRD_GEN ON SECOND_GEN.ID = THIRD_GEN.PARENT_ID
ORDER BY THIRD_GEN.ID ASC