-- 코드를 작성해주세요
WITH RECURSIVE A AS ( 
    SELECT B.ID, 1 AS GENERATION
    FROM ECOLI_DATA AS B
    LEFT JOIN ECOLI_DATA AS C ON B.ID = C.PARENT_ID
    WHERE B.PARENT_ID IS NULL
    
    UNION
    
    SELECT D.ID, A.GENERATION + 1 AS GENERATION
    FROM A
    INNER JOIN ECOLI_DATA AS D ON A.ID = D.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM (
    SELECT A.ID, GENERATION, COUNT(E.ID) AS CHILD_COUNT
    FROM A
    LEFT JOIN ECOLI_DATA AS E ON A.ID = E.PARENT_ID
    GROUP BY A.ID, GENERATION
) AS F
WHERE CHILD_COUNT = 0
GROUP BY GENERATION
ORDER BY GENERATION ASC;